[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

# Add CSP Header
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.hcaptcha.com https://*.captcha.com; frame-src https://*.hcaptcha.com https://*.captcha.com; worker-src 'self' blob:;"
    # You might need to add other domains here depending on your app's needs
    # (e.g., for fonts, images, API calls) 